name: Install Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: compas_wood_3_9_10
          python-version: 3.9
          auto-activate-base: false
          channel-priority: strict
          channels: conda-forge,defaults  # Add defaults if specific packages are not found in conda-forge

      - name: Install dependencies with Conda
        run: |
          echo "Creating Conda environment with Python 3.9"
          conda create --name compas_wood_3_9_10 python=3.9 compas -c conda-forge
          conda activate compas_wood_3_9_10

      - name: Install dependencies with pip
        run: |
          echo "Installing dependencies from requirements.txt..."
          pip install -r requirements.txt
          echo "Installing the package in editable mode..."
          pip install -e .
